# Generated by Django 3.2.2 on 2021-05-17 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to=loja.models.Produto.novo_nome),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to=loja.models.Produto.novo_nome),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to=loja.models.Produto.novo_nome),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to=loja.models.Produto.novo_nome),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto5',
            field=models.ImageField(blank=True, null=True, upload_to=loja.models.Produto.novo_nome),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.PositiveIntegerField()),
                ('logradouro', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
